-- Min's Prep Supabase schema
create extension if not exists pgcrypto;

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  google_auth_id text,
  email text,
  display_name text,
  avatar text,
  created_at timestamptz not null default now()
);

create table if not exists public.problems (
  id text primary key,
  title text not null,
  slug text not null unique,
  topic text not null,
  difficulty text not null check (difficulty in ('Easy','Medium','Hard')),
  external_url text not null,
  order_index int not null unique
);

create table if not exists public.user_problem_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  problem_id text not null references public.problems(id) on delete cascade,
  completed boolean not null default false,
  completed_at timestamptz,
  notes text not null default '',
  review_due_at timestamptz,
  last_reviewed_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (user_id, problem_id)
);

create table if not exists public.user_stats (
  user_id uuid primary key references auth.users(id) on delete cascade,
  xp int not null default 0,
  level int not null default 1,
  current_streak int not null default 0,
  longest_streak int not null default 0,
  streak_freezes_available int not null default 1,
  daily_goal int not null default 2
);

create table if not exists public.achievements (
  id text primary key,
  name text not null,
  description text not null,
  icon text not null
);

create table if not exists public.user_achievements (
  user_id uuid not null references auth.users(id) on delete cascade,
  achievement_id text not null references public.achievements(id) on delete cascade,
  unlocked_at timestamptz not null default now(),
  primary key (user_id, achievement_id)
);

create table if not exists public.notification_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  streak_reminder_enabled boolean not null default true,
  streak_reminder_time time not null default '20:00',
  updated_at timestamptz not null default now()
);

alter table public.notification_settings
  add column if not exists notifications_enabled boolean not null default false,
  add column if not exists daily_prep_reminder_enabled boolean not null default false,
  add column if not exists daily_goal_reminder_enabled boolean not null default false,
  add column if not exists achievement_notifications_enabled boolean not null default false,
  add column if not exists preferred_reminder_time time not null default '20:00',
  add column if not exists timezone text not null default 'UTC',
  add column if not exists created_at timestamptz not null default now();

create table if not exists public.notification_endpoints (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null check (provider in ('fcm', 'web_push')),
  platform text not null check (platform in ('android', 'ios', 'web')),
  device_token text,
  endpoint text,
  p256dh text,
  auth text,
  subscription_metadata jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen_at timestamptz,
  check (
    (provider = 'fcm' and device_token is not null and endpoint is null and p256dh is null and auth is null)
    or
    (provider = 'web_push' and endpoint is not null and p256dh is not null and auth is not null and device_token is null)
  ),
  check (
    (provider = 'fcm' and platform in ('android', 'ios'))
    or
    (provider = 'web_push' and platform = 'web')
  )
);

create unique index if not exists notification_endpoints_fcm_token_key
  on public.notification_endpoints (provider, device_token)
  where device_token is not null and active = true;

create unique index if not exists notification_endpoints_web_endpoint_key
  on public.notification_endpoints (provider, endpoint)
  where endpoint is not null and active = true;

create index if not exists notification_endpoints_user_active_idx
  on public.notification_endpoints (user_id, active);

create table if not exists public.notification_deliveries (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null check (category in ('daily_prep', 'streak', 'daily_goal', 'achievement')),
  local_date date,
  event_identifier text,
  event_version text not null default 'v1',
  status text not null default 'pending' check (status in ('pending', 'sent', 'failed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (category in ('daily_prep', 'streak', 'daily_goal') and local_date is not null and event_identifier is null)
    or
    (category = 'achievement' and local_date is null and event_identifier is not null)
  )
);

create unique index if not exists notification_deliveries_logical_key
  on public.notification_deliveries (
    user_id,
    category,
    coalesce(local_date, date '9999-12-31'),
    coalesce(event_identifier, ''),
    event_version
  );

create index if not exists notification_deliveries_user_category_idx
  on public.notification_deliveries (user_id, category);

alter table public.users enable row level security;
alter table public.problems enable row level security;
alter table public.user_problem_progress enable row level security;
alter table public.user_stats enable row level security;
alter table public.achievements enable row level security;
alter table public.user_achievements enable row level security;
alter table public.notification_settings enable row level security;
alter table public.notification_endpoints enable row level security;
alter table public.notification_deliveries enable row level security;

create policy "users own row" on public.users for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "problems public read" on public.problems for select using (true);
create policy "progress own rows" on public.user_problem_progress for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "stats own rows" on public.user_stats for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "achievements public read" on public.achievements for select using (true);
create policy "user achievements own rows" on public.user_achievements for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "notification settings own rows" on public.notification_settings for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "notification endpoints own rows" on public.notification_endpoints for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

insert into public.achievements (id,name,description,icon) values
('first-blood','First Blood','Complete your first problem.','first_blood'),
('getting-started','Getting Started','Complete 10 problems.','getting_started'),
('momentum','Momentum','Complete 25 problems.','momentum'),
('brain-builder','Brain Builder','Complete 50 problems.','brain_builder'),
('halfway-there','Halfway There','Complete 75 problems.','halfway_there'),
('century','Century','Complete 100 problems.','century'),
('deep-grind','Deep Grind','Complete 125 problems.','deep_grind'),
('tree-climber','Tree Climber','Complete at least one Tree problem.','tree_climber'),
('graph-explorer','Graph Explorer','Complete at least one Graph problem.','graph_explorer'),
('dp-warrior','DP Warrior','Complete at least one Dynamic Programming problem.','dp_warrior'),
('neetcode-master','NeetCode Master','Complete all 150 problems.','neetcode_master'),
('streak-starter','Streak Starter','Reach a 3-day streak.','streak'),
('on-fire','On Fire','Reach a 7-day streak.','fire'),
('daily-grinder','Daily Grinder','Complete the user daily goal on 7 separate days.','daily_grinder'),
('topic-master','Topic Master','Complete 100% of any topic.','topic_master'),
('productive-day','Productive Day','Complete 5 problems in one day.','productive_day'),
('interview-ready','Interview Ready','Complete 5 interview sessions.','interview_ready')
on conflict (id) do nothing;

-- Seed the 150 problems from assets/data/neetcode150.json.
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p001','Contains Duplicate','contains-duplicate','Arrays & Hashing','Easy','https://leetcode.com/problems/contains-duplicate/',1) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p002','Valid Anagram','valid-anagram','Arrays & Hashing','Easy','https://leetcode.com/problems/valid-anagram/',2) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p003','Two Sum','two-sum','Arrays & Hashing','Easy','https://leetcode.com/problems/two-sum/',3) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p004','Group Anagrams','group-anagrams','Arrays & Hashing','Medium','https://leetcode.com/problems/group-anagrams/',4) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p005','Top K Frequent Elements','top-k-frequent-elements','Arrays & Hashing','Medium','https://leetcode.com/problems/top-k-frequent-elements/',5) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p006','Encode and Decode Strings','encode-and-decode-strings','Arrays & Hashing','Medium','https://leetcode.com/problems/encode-and-decode-strings/',6) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p007','Product of Array Except Self','product-of-array-except-self','Arrays & Hashing','Medium','https://leetcode.com/problems/product-of-array-except-self/',7) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p008','Valid Sudoku','valid-sudoku','Arrays & Hashing','Medium','https://leetcode.com/problems/valid-sudoku/',8) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p009','Longest Consecutive Sequence','longest-consecutive-sequence','Arrays & Hashing','Medium','https://leetcode.com/problems/longest-consecutive-sequence/',9) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p010','Valid Palindrome','valid-palindrome','Two Pointers','Easy','https://leetcode.com/problems/valid-palindrome/',10) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p011','Two Sum II - Input Array Is Sorted','two-sum-ii-input-array-is-sorted','Two Pointers','Medium','https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/',11) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p012','3Sum','3sum','Two Pointers','Medium','https://leetcode.com/problems/3sum/',12) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p013','Container With Most Water','container-with-most-water','Two Pointers','Medium','https://leetcode.com/problems/container-with-most-water/',13) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p014','Trapping Rain Water','trapping-rain-water','Two Pointers','Hard','https://leetcode.com/problems/trapping-rain-water/',14) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p015','Best Time to Buy and Sell Stock','best-time-to-buy-and-sell-stock','Sliding Window','Easy','https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',15) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p016','Longest Substring Without Repeating Characters','longest-substring-without-repeating-characters','Sliding Window','Medium','https://leetcode.com/problems/longest-substring-without-repeating-characters/',16) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p017','Longest Repeating Character Replacement','longest-repeating-character-replacement','Sliding Window','Medium','https://leetcode.com/problems/longest-repeating-character-replacement/',17) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p018','Permutation in String','permutation-in-string','Sliding Window','Medium','https://leetcode.com/problems/permutation-in-string/',18) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p019','Minimum Window Substring','minimum-window-substring','Sliding Window','Hard','https://leetcode.com/problems/minimum-window-substring/',19) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p020','Sliding Window Maximum','sliding-window-maximum','Sliding Window','Hard','https://leetcode.com/problems/sliding-window-maximum/',20) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p021','Valid Parentheses','valid-parentheses','Stack','Easy','https://leetcode.com/problems/valid-parentheses/',21) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p022','Min Stack','min-stack','Stack','Medium','https://leetcode.com/problems/min-stack/',22) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p023','Evaluate Reverse Polish Notation','evaluate-reverse-polish-notation','Stack','Medium','https://leetcode.com/problems/evaluate-reverse-polish-notation/',23) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p024','Generate Parentheses','generate-parentheses','Stack','Medium','https://leetcode.com/problems/generate-parentheses/',24) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p025','Daily Temperatures','daily-temperatures','Stack','Medium','https://leetcode.com/problems/daily-temperatures/',25) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p026','Car Fleet','car-fleet','Stack','Medium','https://leetcode.com/problems/car-fleet/',26) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p027','Largest Rectangle in Histogram','largest-rectangle-in-histogram','Stack','Hard','https://leetcode.com/problems/largest-rectangle-in-histogram/',27) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p028','Binary Search','binary-search','Binary Search','Easy','https://leetcode.com/problems/binary-search/',28) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p029','Search a 2D Matrix','search-a-2d-matrix','Binary Search','Medium','https://leetcode.com/problems/search-a-2d-matrix/',29) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p030','Koko Eating Bananas','koko-eating-bananas','Binary Search','Medium','https://leetcode.com/problems/koko-eating-bananas/',30) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p031','Find Minimum in Rotated Sorted Array','find-minimum-in-rotated-sorted-array','Binary Search','Medium','https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/',31) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p032','Search in Rotated Sorted Array','search-in-rotated-sorted-array','Binary Search','Medium','https://leetcode.com/problems/search-in-rotated-sorted-array/',32) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p033','Time Based Key-Value Store','time-based-key-value-store','Binary Search','Medium','https://leetcode.com/problems/time-based-key-value-store/',33) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p034','Median of Two Sorted Arrays','median-of-two-sorted-arrays','Binary Search','Hard','https://leetcode.com/problems/median-of-two-sorted-arrays/',34) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p035','Reverse Linked List','reverse-linked-list','Linked List','Easy','https://leetcode.com/problems/reverse-linked-list/',35) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p036','Merge Two Sorted Lists','merge-two-sorted-lists','Linked List','Easy','https://leetcode.com/problems/merge-two-sorted-lists/',36) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p037','Reorder List','reorder-list','Linked List','Medium','https://leetcode.com/problems/reorder-list/',37) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p038','Remove Nth Node From End of List','remove-nth-node-from-end-of-list','Linked List','Medium','https://leetcode.com/problems/remove-nth-node-from-end-of-list/',38) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p039','Copy List With Random Pointer','copy-list-with-random-pointer','Linked List','Medium','https://leetcode.com/problems/copy-list-with-random-pointer/',39) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p040','Add Two Numbers','add-two-numbers','Linked List','Medium','https://leetcode.com/problems/add-two-numbers/',40) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p041','Linked List Cycle','linked-list-cycle','Linked List','Easy','https://leetcode.com/problems/linked-list-cycle/',41) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p042','Find the Duplicate Number','find-the-duplicate-number','Linked List','Medium','https://leetcode.com/problems/find-the-duplicate-number/',42) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p043','LRU Cache','lru-cache','Linked List','Medium','https://leetcode.com/problems/lru-cache/',43) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p044','Merge K Sorted Lists','merge-k-sorted-lists','Linked List','Hard','https://leetcode.com/problems/merge-k-sorted-lists/',44) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p045','Reverse Nodes in K-Group','reverse-nodes-in-k-group','Linked List','Hard','https://leetcode.com/problems/reverse-nodes-in-k-group/',45) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p046','Invert Binary Tree','invert-binary-tree','Trees','Easy','https://leetcode.com/problems/invert-binary-tree/',46) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p047','Maximum Depth of Binary Tree','maximum-depth-of-binary-tree','Trees','Easy','https://leetcode.com/problems/maximum-depth-of-binary-tree/',47) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p048','Diameter of Binary Tree','diameter-of-binary-tree','Trees','Easy','https://leetcode.com/problems/diameter-of-binary-tree/',48) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p049','Balanced Binary Tree','balanced-binary-tree','Trees','Easy','https://leetcode.com/problems/balanced-binary-tree/',49) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p050','Same Tree','same-tree','Trees','Easy','https://leetcode.com/problems/same-tree/',50) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p051','Subtree of Another Tree','subtree-of-another-tree','Trees','Easy','https://leetcode.com/problems/subtree-of-another-tree/',51) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p052','Lowest Common Ancestor of a Binary Search Tree','lowest-common-ancestor-of-a-binary-search-tree','Trees','Medium','https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/',52) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p053','Binary Tree Level Order Traversal','binary-tree-level-order-traversal','Trees','Medium','https://leetcode.com/problems/binary-tree-level-order-traversal/',53) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p054','Binary Tree Right Side View','binary-tree-right-side-view','Trees','Medium','https://leetcode.com/problems/binary-tree-right-side-view/',54) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p055','Count Good Nodes in Binary Tree','count-good-nodes-in-binary-tree','Trees','Medium','https://leetcode.com/problems/count-good-nodes-in-binary-tree/',55) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p056','Validate Binary Search Tree','validate-binary-search-tree','Trees','Medium','https://leetcode.com/problems/validate-binary-search-tree/',56) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p057','Kth Smallest Element in a BST','kth-smallest-element-in-a-bst','Trees','Medium','https://leetcode.com/problems/kth-smallest-element-in-a-bst/',57) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p058','Construct Binary Tree from Preorder and Inorder Traversal','construct-binary-tree-from-preorder-and-inorder-traversal','Trees','Medium','https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/',58) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p059','Binary Tree Maximum Path Sum','binary-tree-maximum-path-sum','Trees','Hard','https://leetcode.com/problems/binary-tree-maximum-path-sum/',59) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p060','Serialize and Deserialize Binary Tree','serialize-and-deserialize-binary-tree','Trees','Hard','https://leetcode.com/problems/serialize-and-deserialize-binary-tree/',60) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p061','Implement Trie (Prefix Tree)','implement-trie-prefix-tree','Tries','Medium','https://leetcode.com/problems/implement-trie-prefix-tree/',61) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p062','Design Add and Search Words Data Structure','design-add-and-search-words-data-structure','Tries','Medium','https://leetcode.com/problems/design-add-and-search-words-data-structure/',62) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p063','Word Search II','word-search-ii','Tries','Hard','https://leetcode.com/problems/word-search-ii/',63) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p064','Kth Largest Element in a Stream','kth-largest-element-in-a-stream','Heap / Priority Queue','Easy','https://leetcode.com/problems/kth-largest-element-in-a-stream/',64) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p065','Last Stone Weight','last-stone-weight','Heap / Priority Queue','Easy','https://leetcode.com/problems/last-stone-weight/',65) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p066','K Closest Points to Origin','k-closest-points-to-origin','Heap / Priority Queue','Medium','https://leetcode.com/problems/k-closest-points-to-origin/',66) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p067','Kth Largest Element in an Array','kth-largest-element-in-an-array','Heap / Priority Queue','Medium','https://leetcode.com/problems/kth-largest-element-in-an-array/',67) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p068','Task Scheduler','task-scheduler','Heap / Priority Queue','Medium','https://leetcode.com/problems/task-scheduler/',68) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p069','Design Twitter','design-twitter','Heap / Priority Queue','Medium','https://leetcode.com/problems/design-twitter/',69) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p070','Find Median from Data Stream','find-median-from-data-stream','Heap / Priority Queue','Hard','https://leetcode.com/problems/find-median-from-data-stream/',70) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p071','Subsets','subsets','Backtracking','Medium','https://leetcode.com/problems/subsets/',71) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p072','Combination Sum','combination-sum','Backtracking','Medium','https://leetcode.com/problems/combination-sum/',72) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p073','Combination Sum II','combination-sum-ii','Backtracking','Medium','https://leetcode.com/problems/combination-sum-ii/',73) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p074','Permutations','permutations','Backtracking','Medium','https://leetcode.com/problems/permutations/',74) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p075','Subsets II','subsets-ii','Backtracking','Medium','https://leetcode.com/problems/subsets-ii/',75) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p076','Word Search','word-search','Backtracking','Medium','https://leetcode.com/problems/word-search/',76) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p077','Palindrome Partitioning','palindrome-partitioning','Backtracking','Medium','https://leetcode.com/problems/palindrome-partitioning/',77) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p078','Letter Combinations of a Phone Number','letter-combinations-of-a-phone-number','Backtracking','Medium','https://leetcode.com/problems/letter-combinations-of-a-phone-number/',78) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p079','N-Queens','n-queens','Backtracking','Hard','https://leetcode.com/problems/n-queens/',79) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p080','Number of Islands','number-of-islands','Graphs','Medium','https://leetcode.com/problems/number-of-islands/',80) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p081','Clone Graph','clone-graph','Graphs','Medium','https://leetcode.com/problems/clone-graph/',81) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p082','Max Area of Island','max-area-of-island','Graphs','Medium','https://leetcode.com/problems/max-area-of-island/',82) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p083','Pacific Atlantic Water Flow','pacific-atlantic-water-flow','Graphs','Medium','https://leetcode.com/problems/pacific-atlantic-water-flow/',83) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p084','Surrounded Regions','surrounded-regions','Graphs','Medium','https://leetcode.com/problems/surrounded-regions/',84) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p085','Rotting Oranges','rotting-oranges','Graphs','Medium','https://leetcode.com/problems/rotting-oranges/',85) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p086','Walls and Gates','walls-and-gates','Graphs','Medium','https://leetcode.com/problems/walls-and-gates/',86) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p087','Course Schedule','course-schedule','Graphs','Medium','https://leetcode.com/problems/course-schedule/',87) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p088','Course Schedule II','course-schedule-ii','Graphs','Medium','https://leetcode.com/problems/course-schedule-ii/',88) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p089','Graph Valid Tree','graph-valid-tree','Graphs','Medium','https://leetcode.com/problems/graph-valid-tree/',89) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p090','Number of Connected Components in an Undirected Graph','number-of-connected-components-in-an-undirected-graph','Graphs','Medium','https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/',90) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p091','Redundant Connection','redundant-connection','Graphs','Medium','https://leetcode.com/problems/redundant-connection/',91) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p092','Word Ladder','word-ladder','Graphs','Hard','https://leetcode.com/problems/word-ladder/',92) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p093','Reconstruct Itinerary','reconstruct-itinerary','Advanced Graphs','Hard','https://leetcode.com/problems/reconstruct-itinerary/',93) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p094','Min Cost to Connect All Points','min-cost-to-connect-all-points','Advanced Graphs','Medium','https://leetcode.com/problems/min-cost-to-connect-all-points/',94) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p095','Network Delay Time','network-delay-time','Advanced Graphs','Medium','https://leetcode.com/problems/network-delay-time/',95) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p096','Swim in Rising Water','swim-in-rising-water','Advanced Graphs','Hard','https://leetcode.com/problems/swim-in-rising-water/',96) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p097','Alien Dictionary','alien-dictionary','Advanced Graphs','Hard','https://leetcode.com/problems/alien-dictionary/',97) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p098','Cheapest Flights Within K Stops','cheapest-flights-within-k-stops','Advanced Graphs','Medium','https://leetcode.com/problems/cheapest-flights-within-k-stops/',98) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p099','Climbing Stairs','climbing-stairs','1-D Dynamic Programming','Easy','https://leetcode.com/problems/climbing-stairs/',99) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p100','Min Cost Climbing Stairs','min-cost-climbing-stairs','1-D Dynamic Programming','Easy','https://leetcode.com/problems/min-cost-climbing-stairs/',100) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p101','House Robber','house-robber','1-D Dynamic Programming','Medium','https://leetcode.com/problems/house-robber/',101) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p102','House Robber II','house-robber-ii','1-D Dynamic Programming','Medium','https://leetcode.com/problems/house-robber-ii/',102) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p103','Longest Palindromic Substring','longest-palindromic-substring','1-D Dynamic Programming','Medium','https://leetcode.com/problems/longest-palindromic-substring/',103) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p104','Palindromic Substrings','palindromic-substrings','1-D Dynamic Programming','Medium','https://leetcode.com/problems/palindromic-substrings/',104) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p105','Decode Ways','decode-ways','1-D Dynamic Programming','Medium','https://leetcode.com/problems/decode-ways/',105) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p106','Coin Change','coin-change','1-D Dynamic Programming','Medium','https://leetcode.com/problems/coin-change/',106) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p107','Maximum Product Subarray','maximum-product-subarray','1-D Dynamic Programming','Medium','https://leetcode.com/problems/maximum-product-subarray/',107) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p108','Word Break','word-break','1-D Dynamic Programming','Medium','https://leetcode.com/problems/word-break/',108) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p109','Longest Increasing Subsequence','longest-increasing-subsequence','1-D Dynamic Programming','Medium','https://leetcode.com/problems/longest-increasing-subsequence/',109) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p110','Partition Equal Subset Sum','partition-equal-subset-sum','1-D Dynamic Programming','Medium','https://leetcode.com/problems/partition-equal-subset-sum/',110) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p111','Unique Paths','unique-paths','2-D Dynamic Programming','Medium','https://leetcode.com/problems/unique-paths/',111) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p112','Longest Common Subsequence','longest-common-subsequence','2-D Dynamic Programming','Medium','https://leetcode.com/problems/longest-common-subsequence/',112) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p113','Best Time to Buy and Sell Stock with Cooldown','best-time-to-buy-and-sell-stock-with-cooldown','2-D Dynamic Programming','Medium','https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/',113) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p114','Coin Change II','coin-change-ii','2-D Dynamic Programming','Medium','https://leetcode.com/problems/coin-change-ii/',114) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p115','Target Sum','target-sum','2-D Dynamic Programming','Medium','https://leetcode.com/problems/target-sum/',115) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p116','Interleaving String','interleaving-string','2-D Dynamic Programming','Medium','https://leetcode.com/problems/interleaving-string/',116) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p117','Longest Increasing Path in a Matrix','longest-increasing-path-in-a-matrix','2-D Dynamic Programming','Hard','https://leetcode.com/problems/longest-increasing-path-in-a-matrix/',117) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p118','Distinct Subsequences','distinct-subsequences','2-D Dynamic Programming','Hard','https://leetcode.com/problems/distinct-subsequences/',118) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p119','Edit Distance','edit-distance','2-D Dynamic Programming','Hard','https://leetcode.com/problems/edit-distance/',119) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p120','Burst Balloons','burst-balloons','2-D Dynamic Programming','Hard','https://leetcode.com/problems/burst-balloons/',120) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p121','Regular Expression Matching','regular-expression-matching','2-D Dynamic Programming','Hard','https://leetcode.com/problems/regular-expression-matching/',121) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p122','Maximum Subarray','maximum-subarray','Greedy','Medium','https://leetcode.com/problems/maximum-subarray/',122) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p123','Jump Game','jump-game','Greedy','Medium','https://leetcode.com/problems/jump-game/',123) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p124','Jump Game II','jump-game-ii','Greedy','Medium','https://leetcode.com/problems/jump-game-ii/',124) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p125','Gas Station','gas-station','Greedy','Medium','https://leetcode.com/problems/gas-station/',125) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p126','Hand of Straights','hand-of-straights','Greedy','Medium','https://leetcode.com/problems/hand-of-straights/',126) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p127','Merge Triplets to Form Target Triplet','merge-triplets-to-form-target-triplet','Greedy','Medium','https://leetcode.com/problems/merge-triplets-to-form-target-triplet/',127) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p128','Partition Labels','partition-labels','Greedy','Medium','https://leetcode.com/problems/partition-labels/',128) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p129','Valid Parenthesis String','valid-parenthesis-string','Greedy','Medium','https://leetcode.com/problems/valid-parenthesis-string/',129) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p130','Insert Interval','insert-interval','Intervals','Medium','https://leetcode.com/problems/insert-interval/',130) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p131','Merge Intervals','merge-intervals','Intervals','Medium','https://leetcode.com/problems/merge-intervals/',131) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p132','Non-Overlapping Intervals','non-overlapping-intervals','Intervals','Medium','https://leetcode.com/problems/non-overlapping-intervals/',132) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p133','Meeting Rooms','meeting-rooms','Intervals','Easy','https://leetcode.com/problems/meeting-rooms/',133) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p134','Meeting Rooms II','meeting-rooms-ii','Intervals','Medium','https://leetcode.com/problems/meeting-rooms-ii/',134) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p135','Minimum Interval to Include Each Query','minimum-interval-to-include-each-query','Intervals','Hard','https://leetcode.com/problems/minimum-interval-to-include-each-query/',135) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p136','Rotate Image','rotate-image','Math & Geometry','Medium','https://leetcode.com/problems/rotate-image/',136) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p137','Spiral Matrix','spiral-matrix','Math & Geometry','Medium','https://leetcode.com/problems/spiral-matrix/',137) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p138','Set Matrix Zeroes','set-matrix-zeroes','Math & Geometry','Medium','https://leetcode.com/problems/set-matrix-zeroes/',138) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p139','Happy Number','happy-number','Math & Geometry','Easy','https://leetcode.com/problems/happy-number/',139) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p140','Plus One','plus-one','Math & Geometry','Easy','https://leetcode.com/problems/plus-one/',140) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p141','Pow(x, n)','powx-n','Math & Geometry','Medium','https://leetcode.com/problems/powx-n/',141) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p142','Multiply Strings','multiply-strings','Math & Geometry','Medium','https://leetcode.com/problems/multiply-strings/',142) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p143','Detect Squares','detect-squares','Math & Geometry','Medium','https://leetcode.com/problems/detect-squares/',143) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p144','Single Number','single-number','Bit Manipulation','Easy','https://leetcode.com/problems/single-number/',144) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p145','Number of 1 Bits','number-of-1-bits','Bit Manipulation','Easy','https://leetcode.com/problems/number-of-1-bits/',145) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p146','Counting Bits','counting-bits','Bit Manipulation','Easy','https://leetcode.com/problems/counting-bits/',146) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p147','Reverse Bits','reverse-bits','Bit Manipulation','Easy','https://leetcode.com/problems/reverse-bits/',147) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p148','Missing Number','missing-number','Bit Manipulation','Easy','https://leetcode.com/problems/missing-number/',148) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p149','Sum of Two Integers','sum-of-two-integers','Bit Manipulation','Medium','https://leetcode.com/problems/sum-of-two-integers/',149) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
insert into public.problems (id,title,slug,topic,difficulty,external_url,order_index) values ('p150','Reverse Integer','reverse-integer','Bit Manipulation','Medium','https://leetcode.com/problems/reverse-integer/',150) on conflict (id) do update set title=excluded.title, slug=excluded.slug, topic=excluded.topic, difficulty=excluded.difficulty, external_url=excluded.external_url, order_index=excluded.order_index;
